### ISSUE TITLE
Using callback with classes.

### ISSUE THREAD

**Issue by Jakub-S-K** [khoih-prog/ESP8266TimerInterrupt#10]
Since few days I was trying to write simple class which has few status variables and every X milliseconds it updates itself via ISR interrupt. My Question is how I can pass object to callback function. Callback isn't taking any parameters ex. void* with which I possibly could pass my object and assign interrupt with specific object, how could I achieve that? edit: Sorry, my english is not very good.

**Comment by khoih-prog** [comment]
Thanks for your interest in the library.

Better knowledge(programming, hardware, etc.)  is required to use the ISR features correctly. It seems that you need to know that ISR is not normal function and normally doesn't expect to receive parameters such as objects.

Also be careful when you use **global volatile** complicated objects inside ISRs.

That's all I can say, and you have to do more **Google research** / ask on **public forum** as I don't have time to explain everything.

Good Luck,
