### ISSUE TITLE
ESP8266TimerInterrupt listing is outdated

### ISSUE THREAD

**Issue by khoih-prog** [khoih-prog/ESP8266TimerInterrupt#12]
Hi @cdzombak

I saw your post in PIO forum [ESP8266TimerInterrupt listing is outdated](https://community.platformio.org/t/esp8266timerinterrupt-listing-is-outdated/23842)

I suggest you use the latest PIO from author `khoih.prog` not `khoih-prog`, such as [**PIO ESP8266TimerInterrupt Installation**](https://platformio.org/lib/show/11385/ESP8266TimerInterrupt/installation)

Similar issue happened to many of my libraries, that's why I had to create a new author `khoih.prog` to be sure all libraries are updated with latest versions.

For example, check [**PlatformIO only has version 1.3.0** #65](https://github.com/khoih-prog/ESP_WiFiManager/issues/65)

**Comment by cdzombak** [comment]
I see. Thanks for the note!

**Comment by ivankravets** [comment]
Hi @khoih-prog,

Please contact us next time if you have any issues with PlatformIO Registry. We removed ~80 duplicated libraries and merged the rest to the `khoih-prog` account. The `khoih.prog` has been removed.

Please check that you have access to the `khoih-prog` account. The confirmation email has been sent. You can also login with Github via `pio home` -> Account -> Login.

**Comment by khoih-prog** [comment]
@ivankravets 

Hopefully there is no new issue for your users.

What will happen to users already use the `khoih.prog` libraries? Can you just delete the libraries without any side-effects ? Why don't you just merge them ? Will the `khoih-prog` libraries be updated automatically from now on ?

**Comment by ivankravets** [comment]
> What will happen to users already use the khoih.prog libraries? 

There are not so many downloads. Users use `khoih-prog` libraries. If the library was installed from `khoih.prog`, user will stay with this version until change dependency to `khoih-prog`.

> Can you just delete the libraries without any side-effects ? 

Users who already installed libraries from `khoih.prog` owner will not be affected.

> Why don't you just merge them ? 
We merge them and removed duplicates.

> Will the khoih-prog libraries be updated automatically from now on ?

It depends on the library. If you previously manually published it to the registry, it will not be updated automatically until you repeat publishing procedure.

**Comment by khoih-prog** [comment]
> It depends on the library. If you previously manually published it to the registry, it will not be updated automatically until you repeat publishing procedure.

The reason the new `khoih.prog` was created is that many libraries were not updated automatically, even updated in Arduino Library Manager.

I've just checked and many `khoih-prog` libraries are still not auto-updated yet, for example

- "khoih-prog/Blynk_WiFiManager" still at v1.0.16, while latest in Arduino is v1.6.1

It's really time-consuming to have to go thru every of them to check, and update every release. I guess merging is much better way.

What do you think the best way to do?

**Comment by khoih-prog** [comment]
@ivankravets 

Sorry for previous post. I see now you've merged and update the outdated `khoih-prog` to the latest of `khoih.prog`

Now I have to update all the `platforn,ini` and `library.json` to remove the `khoih.prog` to avoid errors

Many thanks,

**Comment by ivankravets** [comment]
Yes, just update library dependecies. 

Thanks for using PlatformIO!
