### ISSUE TITLE
ISR_Timer callback function is not getting called

### ISSUE THREAD

**Issue by rohitranjan1991** [khoih-prog/ESP8266TimerInterrupt#2]
Hi, Thanks for the Library.
               Can you please check why is my callback function not getting called in the below program ? Please ignore the rest of the program.

> #include "hw_timer.h" 
> #include "ESP8266TimerInterrupt.h"
> #include "ESP8266_ISR_Timer.h"
> #define TIMER_INTERVAL_MS1        1000 
> #define TIMER_INTERVAL_MS2        2000 
> const byte zcPin = 12;
> const byte pwmPin = 13;
> uint32_t ts1 = micros();
> uint32_t diff1 = micros();
> 
> uint32_t ts2 = millis();
> uint32_t diff2 = millis();
> 
> bool hasDitectedZC = false;
> byte zcState = 0;
> int dimDelay = 8550;
> 
> 
> void ICACHE_RAM_ATTR zcDetectISR ();
> //ESP8266Timer ITimer;
> //ESP8266Timer ITimer2;
> ESP8266_ISR_Timer ISR_Timer;
> 
> **void ICACHE_RAM_ATTR TimerHandler()**
> **{**
>    
>     diff1 = millis() - ts1;
>     ts1 = millis();
>     
>     Serial.println("Called TimerHandler1");
> **}**
> 
> void ICACHE_RAM_ATTR TimerHandler2()
> {
>     diff2 = millis() - ts2;
>     ts2 = millis();
>     Serial.println("Called TimerHandler2");
> }
> 
> 
> 
> 
> **void setup()** {
>   // put your setup code here, to run once:
>   Serial.begin(9600); 
>   Serial.println("Initializing the program");
>   pinMode(zcPin, INPUT_PULLUP);
> //  pinMode(pwmPin, OUTPUT);
> 
>   attachInterrupt(zcPin, zcDetectISR, RISING);    // Attach an Interupt to Pin 2 (interupt 0) for Zero Cross Detection
> //  hw_timer_init(NMI_SOURCE, 0);
> //  hw_timer_set_func(dimTimerISR);
> 
> //  if (ITimer.attachInterruptInterval(TIMER_INTERVAL_MS1 * 1000, TimerHandler))
> //    Serial.println("Starting  ITimer1 OK, millis() = " + String(millis()));
> //
> //   if (ITimer2.attachInterruptInterval(TIMER_INTERVAL_MS2 * 1000, TimerHandler2))
> //    Serial.println("Starting  ITimer2 OK, millis() = " + String(millis()));
> 
>   **ISR_Timer.setInterval(2000L, TimerHandler);**
>      **ISR_Timer.run();**
> }
> 
> **void loop() {**
>   // put your main code here, to run repeatedly:
> //  delay(500);
> //if(diff > 11000 || diff < 9000)
> //{  Serial.print("Zero Cross Deletection Frequency : ");
> //  Serial.print(diff);
> //  Serial.print(" micro Second");
> //  Serial.println();
> //} 
> **delay(2000);**
> **Serial.print("Diff1 : ");**
> **Serial.println(diff1);**
> //Serial.print("Diff2 : ");
> //Serial.println(diff2);
> }
> 
> 
> 
> void dimTimerISR(){
>     digitalWrite(pwmPin, 0);
>     delayMicroseconds(100);
>     digitalWrite(pwmPin, 1);
>     zcState = 0;
> }
> 
> void initiateDimmer(){
>   if(zcState == 0)
>   {
>     digitalWrite(pwmPin, 1); // off
> //    hw_timer_arm(dimDelay); 
>   }
> }
> 
> void zcDetectISR(){
>   if(!hasDitectedZC)
>   {
>     hasDitectedZC = true;
> //    initiateDimmer();
>   }
> //  diff = micros()-ts1;
> //  ts1 = micros();
> }

**Comment by khoih-prog** [comment]
You comment them out and disable the **TimerHandler**
//ESP8266Timer ITimer;
...
// if (ITimer.attachInterruptInterval(TIMER_INTERVAL_MS1 * 1000, TimerHandler))
// Serial.println("Starting ITimer1 OK, millis() = " + String(millis()));

**Comment by rohitranjan1991** [comment]
can you please elaborate as to what should i be doing  to fix the above code ?

**Comment by khoih-prog** [comment]
I suggest you restart with a simplest example [Argument_None](https://github.com/khoih-prog/ESP8266TimerInterrupt/tree/master/examples/Argument_None) and try to understand it before going forward. Then compare the **differences** between the usages.
Then you'll find out why. This way it'll be more beneficial for you in the future, especially when using the _ISR-based_ features.
