### ISSUE TITLE
unattach ?

### ISSUE THREAD

**Issue by wuzi42** [khoih-prog/ESP8266TimerInterrupt#24]
Hi Khoih,
thank you very much for the esp8266interrupt library!
Could you please tell me howto stop calling the interrupt handler routine correctly?
thank you again
Wulf

**Comment by wuzi42** [comment]
Hi Khoih,
thank you very much for the esp8266interrupt library!
Could you please tell me howto stop calling the interrupt handler routine correctly?
thank you again
Wulf

**Comment by khoih-prog** [comment]
Hi @wuzi42 

Thanks for using the lbrary.

You can either

1. detach the Timer1 Interrupt `Calback function` completely.

```
timer1_detachInterrupt();
```

then to reuse with the same `Calback function`

```
reattachInterrupt();
```

or new `Calback function`

```
attachInterrupt(frequency, newCallback);
```

2.  temporarily disable Timer1 Interrupt

```
detachInterrupt();
// or
//disableTimer();
// or
//stopTimer();
```

 and easily reuse later, with the same `Calback function`, by

```
enableTimer();
// or
//restartTimer();
```

**Comment by wuzi42** [comment]
Hi Khoi
thank you for your detailed answer!




***@***.***
 
From: Khoi Hoang
Date: 2022-04-25 22:54
To: khoih-prog/ESP8266TimerInterrupt
CC: wuzi42; Mention
Subject: Re: [khoih-prog/ESP8266TimerInterrupt] unattach ? (Issue #24)
Hi @wuzi42
Thanks for using the lbrary.
You can either
detach the Timer1 Interrupt Calback function completely.
timer1_detachInterrupt();

then to reuse with the same Calback function
reattachInterrupt();

or new Calback function
attachInterrupt(frequency, newCallback);

temporarily disable Timer1 Interrupt
detachInterrupt();
// or
//disableTimer();
// or
//stopTimer();

and easily reuse later, with the same Calback function, by
enableTimer();
// or
//restartTimer();
