### ISSUE TITLE
analogWriteRange broke interrupts

### ISSUE THREAD

**Issue by andreydk1981** [khoih-prog/ESP8266TimerInterrupt#27]
Hello. Thanks for the library.
I made a project using your library and everything worked fine, until I decided to add a control for the brightness of the display backlight from the readings of the photoresistor.
I added just a few lines and interrupts stopped working.

I added to the setup:
 analogWriteRange(1023);
 analogWrite(D3, 1023);

and in loop:
int light = analogRead(A0);
analogWrite(D3, 1023-light);

I commented out these lines, but interrupts don't work now. I assume that the matter is in analogWriteRange(1023);
How to make the library work again? I tried analogWriteRange(256) but it doesn't help....

**Comment by khoih-prog** [comment]
Hi @andreydk1981 

Thanks for your usage of the library.

As you know, using TimerInterrupt / ISR requires certain basic kind of hardware-related knowledge about the hardware, Hardware Timer.

I suggest you read the [**HOWTO Use PWM analogWrite() with ESP8266 running Timer1 Interrupt**](https://github.com/khoih-prog/ESP8266TimerInterrupt#howto-use-pwm-analogwrite-with-esp8266-running-timer1-interrupt) and find out yourself why to enrich your knowledge.

Also it's always better to go thru the examples, and read

https://github.com/khoih-prog/ESP8266TimerInterrupt/blob/8a003893199a999b4c3ef7e56a86f306ab08937b/examples/Argument_None/Argument_None.ino#L9-L12

>   The ESP8266 timers are badly designed, using only 23-bit counter along with maximum 256 prescaler. They're only better than UNO / Mega.
>   The ESP8266 has two hardware timers, but timer0 has been used for WiFi and it's not advisable to use. Only timer1 is available.
>   The timer1's 23-bit counter terribly can count only up to 8,388,607. So the timer1 maximum interval is very short.
>   Using 256 prescaler, maximum timer1 interval is only 26.843542 seconds !!!

If you're interested, you can help yourself by adapting my [**FakeAnalogWrite** example](https://github.com/khoih-prog/NRF52_MBED_TimerInterrupt/tree/main/examples/FakeAnalogWrite) to replace the ESP8266 analogWrite().

You also can use the better ESP32, with more TimerInterrupts to use.

Good Luck,

**Comment by andreydk1981** [comment]
The fact is that I no longer need analogWrite and I removed them, but now interrupts do not work. Apparently something changed when I wanted to use them. I don't know how to make interrupts work again without analogWrite...

**Comment by khoih-prog** [comment]
Start to use the examples first. I won't spend anymore time here.

Ask on some Forums for help if necessary.

Good Luck,
