### ISSUE TITLE
**The cycle is 1ms, esp8266 is easy to crash**

### ISSUE THREAD

**Issue by small-zz** [khoih-prog/ESP8266TimerInterrupt#5]
void ICACHE_RAM_ATTR TimerHandler(void)
{
	Serial.println("1");
}
if (ITimer.attachInterruptInterval(TIMER_INTERVAL_MS*5, TimerHandler))
  {
    DEBUG_LN("Starting  ITimer OK");
  }
  else
    DEBUG_LN("Can't set ITimer correctly. Select another freq. or interval");

**It will crash after running for a while**
`Exception (0):
epc1=0x4020140c epc2=0x00000000 epc3=0x00000000 excvaddr=0x00000000 depc=0x00000000

>>>stack>>>

ctx: sys
sp: 3fffec10 end: 3fffffb0 offset: 0190
3fffeda0:  00000000 3ffedc70 00000002 401003c8  
3fffedb0:  402163c0 3ffeea94 3ffeb597 401001f8  
3fffedc0:  4021d131 3fffee80 3fffc230 4000050c  
3fffedd0:  4000437b 00000030 00000010 ffffffff  
3fffede0:  60000200 00000008 00020300 80000000  
3fffedf0:  20000000 3ffef6e8 80000000 200fc1a0  
3fffee00:  80000000 3fffc6fc 00000001 3ffef6ec  
3fffee10:  000000d4 000fc1a0 60000600 00000030  
3fffee20:  40216e05 401001b0 00000020 40100105  
3fffee30:  401016cd 004d29cf 3ffeeaac 00000000  
3fffee40:  3ffe8830 3ffeeaac 00000000 4021b87b  
3fffee50:  00000000 00308d97 4021b8e6 3ffeeaac  
3fffee60:  3ffeea94 ffffffe3 00000000 ffffffff  
3fffee70:  40000f3d 00000023 00000000 3fffd9d0  
3fffee80:  00000000 00310808 00640104 00000047  
3fffee90:  3ffeb530 000000ea 3ffeb547 3ffeb524  
3fffeea0:  00000c70 4bc6a7f0 36872b02 00000000  
3fffeeb0:  00000000 00000000 4bc6a7f0 60000600  
3fffeec0:  00000002 400042db 00000020 40100a58  
3fffeed0:  40004b31 3ffef5cc 000001f4 000fc080  
3fffeee0:  40102164 3ffecdb0 3ffe8fb0 40100cb0  
3fffeef0:  40102391 3ffef5cc 00000000 009c0be8  
3fffef00:  009be30e 3ffe8830 3ffe8fb0 40231cd6  
3fffef10:  40230d09 40230d12 3ffe8e24 3ffe8830  
3fffef20:  40223e65 3ffe8e24 3ffe8830 009be30e  
3fffef30:  40223eaa 3fffdab0 00000000 3fffdcb0  
3fffef40:  3ffe8848 3fffdad0 3ffee39c 40201928  
3fffef50:  40000f49 40000f49 3fffdab0 40000f49  
3fffef60:  40000e19 00000005 00040f10 00000000  
3fffef70:  00000000 aa55aa55 00000012 40100e39  
3fffef80:  40100e3f 00040f10 00000000 0c0c5200  
3fffef90:  4010000d 40503450 09614283 2200d416  
3fffefa0:  00000000 3fffef3c 00000000 00000000  
3fffefb0:  3fffffc0 00000000 00000000 feefeffe  
3fffefc0:  feefeffe feefeffe feefeffe feefeffe  
3fffefd0:  feefeffe feefeffe feefeffe feefeffe  
3fffefe0:  feefeffe feefeffe feefeffe feefeffe  
3fffeff0:  feefeffe feefeffe feefeffe feefeffe  
3ffff000:  feefeffe feefeffe feefeffe feefeffe  
3ffff010:  feefeffe feefeffe feefeffe feefeffe  
3ffff020:  feefeffe feefeffe feefeffe feefeffe  
3ffff030:  feefeffe feefeffe feefeffe feefeffe  
3ffff040:  feefeffe feefeffe feefeffe feefeffe  
3ffff050:  feefeffe feefeffe feefeffe feefeffe  
3ffff060:  feefeffe feefeffe feefeffe feefeffe  
3ffff070:  feefeffe feefeffe feefeffe feefeffe  
3ffff080:  feefeffe feefeffe feefeffe feefeffe  
3ffff090:  feefeffe feefeffe feefeffe feefeffe  
3ffff0a0:  feefeffe feefeffe feefeffe feefeffe  
3ffff0b0:  feefeffe feefeffe feefeffe feefeffe  
3ffff0c0:  feefeffe feefeffe feefeffe feefeffe  
3ffff0d0:  feefeffe feefeffe feefeffe feefeffe  
3ffff0e0:  feefeffe feefeffe feefeffe feefeffe  
3ffff0f0:  feefeffe feefeffe feefeffe feefeffe  
3ffff100:  feefeffe feefeffe feefeffe feefeffe  
3ffff110:  feefeffe feefeffe feefeffe feefeffe  
3ffff120:  feefeffe feefeffe feefeffe feefeffe  
3ffff130:  feefeffe feefeffe feefeffe feefeffe  
3ffff140:  feefeffe feefeffe feefeffe feefeffe  
3ffff150:  feefeffe feefeffe feefeffe feefeffe  
3ffff160:  feefeffe feefeffe feefeffe feefeffe  
3ffff170:  feefeffe feefeffe feefeffe feefeffe  
3ffff180:  feefeffe feefeffe feefeffe feefeffe  
3ffff190:  feefeffe feefeffe feefeffe feefeffe  
3ffff1a0:  feefeffe feefeffe feefeffe feefeffe  
3ffff1b0:  feefeffe feefeffe feefeffe feefeffe  
3ffff1c0:  feefeffe feefeffe feefeffe feefeffe  
3ffff1d0:  feefeffe feefeffe feefeffe feefeffe  
3ffff1e0:  feefeffe feefeffe feefeffe feefeffe  
3ffff1f0:  feefeffe feefeffe feefeffe feefeffe  
3ffff200:  feefeffe feefeffe feefeffe feefeffe  
3ffff210:  feefeffe feefeffe feefeffe feefeffe  
3ffff220:  feefeffe feefeffe feefeffe feefeffe  
3ffff230:  feefeffe feefeffe feefeffe feefeffe  
3ffff240:  feefeffe feefeffe feefeffe feefeffe  
3ffff250:  feefeffe feefeffe feefeffe feefeffe  
3ffff260:  feefeffe feefeffe feefeffe feefeffe  
3ffff270:  feefeffe feefeffe feefeffe feefeffe  
3ffff280:  feefeffe feefeffe feefeffe feefeffe  
3ffff290:  feefeffe feefeffe feefeffe feefeffe  
3ffff2a0:  feefeffe feefeffe feefeffe feefeffe  
3ffff2b0:  feefeffe feefeffe feefeffe feefeffe  
3ffff2c0:  feefeffe feefeffe feefeffe feefeffe  
3ffff2d0:  feefeffe feefeffe feefeffe feefeffe  
3ffff2e0:  feefeffe feefeffe feefeffe feefeffe  
3ffff2f0:  feefeffe feefeffe feefeffe feefeffe  
3ffff300:  feefeffe feefeffe feefeffe feefeffe  
3ffff310:  feefeffe feefeffe feefeffe feefeffe  
3ffff320:  feefeffe feefeffe feefeffe feefeffe  
3ffff330:  feefeffe feefeffe feefeffe feefeffe  
3ffff340:  feefeffe feefeffe feefeffe feefeffe  
3ffff350:  feefeffe feefeffe feefeffe feefeffe  
3ffff360:  feefeffe feefeffe feefeffe feefeffe  
3ffff370:  feefeffe feefeffe feefeffe feefeffe  
3ffff380:  feefeffe feefeffe feefeffe feefeffe  
3ffff390:  feefeffe feefeffe feefeffe feefeffe  
3ffff3a0:  feefeffe feefeffe feefeffe feefeffe  
3ffff3b0:  feefeffe feefeffe feefeffe feefeffe  
3ffff3c0:  feefeffe feefeffe feefeffe feefeffe  
3ffff3d0:  feefeffe feefeffe feefeffe feefeffe  
3ffff3e0:  feefeffe feefeffe feefeffe feefeffe  
3ffff3f0:  feefeffe feefeffe feefeffe feefeffe  
3ffff400:  feefeffe feefeffe feefeffe feefeffe  
3ffff410:  feefeffe feefeffe feefeffe feefeffe  
3ffff420:  feefeffe feefeffe feefeffe feefeffe  
3ffff430:  feefeffe feefeffe feefeffe feefeffe  
3ffff440:  feefeffe feefeffe feefeffe feefeffe  
3ffff450:  feefeffe feefeffe feefeffe feefeffe  
3ffff460:  feefeffe feefeffe feefeffe feefeffe  
3ffff470:  feefeffe feefeffe feefeffe feefeffe  
3ffff480:  feefeffe feefeffe feefeffe feefeffe  
3ffff490:  feefeffe feefeffe feefeffe feefeffe  
3ffff4a0:  feefeffe feefeffe feefeffe feefeffe  
3ffff4b0:  feefeffe feefeffe feefeffe feefeffe  
3ffff4c0:  feefeffe feefeffe feefeffe feefeffe  
3ffff4d0:  feefeffe feefeffe feefeffe feefeffe  
3ffff4e0:  feefeffe feefeffe feefeffe feefeffe  
3ffff4f0:  feefeffe feefeffe feefeffe feefeffe  
3ffff500:  feefeffe feefeffe feefeffe feefeffe  
3ffff510:  feefeffe feefeffe feefeffe feefeffe  
3ffff520:  feefeffe feefeffe feefeffe feefeffe  
3ffff530:  feefeffe feefeffe feefeffe feefeffe  
3ffff540:  feefeffe feefeffe feefeffe feefeffe  
3ffff550:  feefeffe feefeffe feefeffe feefeffe  
3ffff560:  feefeffe feefeffe feefeffe feefeffe  
3ffff570:  feefeffe feefeffe feefeffe feefeffe  
3ffff580:  feefeffe feefeffe feefeffe feefeffe  
3ffff590:  feefeffe feefeffe feefeffe feefeffe  
3ffff5a0:  feefeffe feefeffe feefeffe feefeffe  
3ffff5b0:  feefeffe feefeffe feefeffe feefeffe  
3ffff5c0:  feefeffe feefeffe feefeffe feefeffe  
3ffff5d0:  feefeffe feefeffe feefeffe feefeffe  
3ffff5e0:  feefeffe feefeffe feefeffe feefeffe  
3ffff5f0:  feefeffe feefeffe feefeffe feefeffe  
3ffff600:  feefeffe feefeffe feefeffe feefeffe  
3ffff610:  feefeffe feefeffe feefeffe feefeffe  
3ffff620:  feefeffe feefeffe feefeffe feefeffe  
3ffff630:  feefeffe feefeffe feefeffe feefeffe  
3ffff640:  feefeffe feefeffe feefeffe feefeffe  
3ffff650:  feefeffe feefeffe feefeffe feefeffe  
3ffff660:  feefeffe feefeffe feefeffe feefeffe  
3ffff670:  feefeffe feefeffe feefeffe feefeffe  
3ffff680:  feefeffe feefeffe feefeffe feefeffe  
3ffff690:  feefeffe feefeffe feefeffe feefeffe  
3ffff6a0:  feefeffe feefeffe feefeffe feefeffe  
3ffff6b0:  feefeffe feefeffe feefeffe feefeffe  
3ffff6c0:  feefeffe feefeffe feefeffe feefeffe  
3ffff6d0:  feefeffe feefeffe feefeffe feefeffe  
3ffff6e0:  feefeffe feefeffe feefeffe feefeffe  
3ffff6f0:  feefeffe feefeffe feefeffe feefeffe  
3ffff700:  feefeffe feefeffe feefeffe feefeffe  
3ffff710:  feefeffe feefeffe feefeffe feefeffe  
3ffff720:  feefeffe feefeffe feefeffe feefeffe  
3ffff730:  feefeffe feefeffe feefeffe feefeffe  
3ffff740:  feefeffe feefeffe feefeffe feefeffe  
3ffff750:  feefeffe feefeffe feefeffe feefeffe  
3ffff760:  feefeffe feefeffe feefeffe feefeffe  
3ffff770:  feefeffe feefeffe feefeffe feefeffe  
3ffff780:  feefeffe feefeffe feefeffe feefeffe  
3ffff790:  feefeffe feefeffe feefeffe feefeffe  
3ffff7a0:  feefeffe feefeffe feefeffe feefeffe  
3ffff7b0:  feefeffe feefeffe feefeffe feefeffe  
3ffff7c0:  feefeffe feefeffe feefeffe feefeffe  
3ffff7d0:  feefeffe feefeffe feefeffe feefeffe  
3ffff7e0:  feefeffe feefeffe feefeffe feefeffe  
3ffff7f0:  feefeffe feefeffe feefeffe feefeffe  
3ffff800:  feefeffe feefeffe feefeffe feefeffe  
3ffff810:  feefeffe feefeffe feefeffe feefeffe  
3ffff820:  feefeffe feefeffe feefeffe feefeffe  
3ffff830:  feefeffe feefeffe feefeffe feefeffe  
3ffff840:  feefeffe feefeffe feefeffe feefeffe  
3ffff850:  feefeffe feefeffe feefeffe feefeffe  
3ffff860:  feefeffe feefeffe feefeffe feefeffe  
3ffff870:  feefeffe feefeffe feefeffe feefeffe  
3ffff880:  feefeffe feefeffe feefeffe feefeffe  
3ffff890:  feefeffe feefeffe feefeffe feefeffe  
3ffff8a0:  feefeffe feefeffe feefeffe feefeffe  
3ffff8b0:  feefeffe feefeffe feefeffe feefeffe  
3ffff8c0:  feefeffe feefeffe feefeffe feefeffe  
3ffff8d0:  feefeffe feefeffe feefeffe feefeffe  
3ffff8e0:  feefeffe feefeffe feefeffe feefeffe  
3ffff8f0:  feefeffe feefeffe feefeffe feefeffe  
3ffff900:  feefeffe feefeffe feefeffe feefeffe  
3ffff910:  feefeffe feefeffe feefeffe feefeffe  
3ffff920:  feefeffe feefeffe feefeffe feefeffe  
3ffff930:  feefeffe feefeffe feefeffe feefeffe  
3ffff940:  feefeffe feefeffe feefeffe feefeffe  
3ffff950:  feefeffe feefeffe feefeffe feefeffe  
3ffff960:  feefeffe feefeffe feefeffe feefeffe  
3ffff970:  feefeffe feefeffe feefeffe feefeffe  
3ffff980:  feefeffe feefeffe feefeffe feefeffe  
3ffff990:  feefeffe feefeffe feefeffe feefeffe  
3ffff9a0:  feefeffe feefeffe feefeffe feefeffe  
3ffff9b0:  feefeffe feefeffe feefeffe feefeffe  
3ffff9c0:  feefeffe feefeffe feefeffe feefeffe  
3ffff9d0:  feefeffe feefeffe feefeffe feefeffe  
3ffff9e0:  feefeffe feefeffe feefeffe feefeffe  
3ffff9f0:  feefeffe feefeffe feefeffe feefeffe  
3ffffa00:  feefeffe feefeffe feefeffe feefeffe  
3ffffa10:  feefeffe feefeffe feefeffe feefeffe  
3ffffa20:  feefeffe feefeffe feefeffe feefeffe  
3ffffa30:  feefeffe feefeffe feefeffe feefeffe  
3ffffa40:  feefeffe feefeffe feefeffe feefeffe  
3ffffa50:  feefeffe feefeffe feefeffe feefeffe  
3ffffa60:  feefeffe feefeffe feefeffe feefeffe  
3ffffa70:  feefeffe feefeffe feefeffe feefeffe  
3ffffa80:  feefeffe feefeffe feefeffe feefeffe  
3ffffa90:  feefeffe feefeffe feefeffe feefeffe  
3ffffaa0:  feefeffe feefeffe feefeffe feefeffe  
3ffffab0:  feefeffe feefeffe feefeffe feefeffe  
3ffffac0:  feefeffe feefeffe feefeffe feefeffe  
3ffffad0:  feefeffe feefeffe feefeffe feefeffe  
3ffffae0:  feefeffe feefeffe feefeffe feefeffe  
3ffffaf0:  feefeffe feefeffe feefeffe feefeffe  
3ffffb00:  feefeffe feefeffe feefeffe feefeffe  
3ffffb10:  feefeffe feefeffe feefeffe feefeffe  
3ffffb20:  feefeffe feefeffe feefeffe feefeffe  
3ffffb30:  feefeffe feefeffe feefeffe feefeffe  
3ffffb40:  feefeffe feefeffe feefeffe feefeffe  
3ffffb50:  feefeffe feefeffe feefeffe feefeffe  
3ffffb60:  feefeffe feefeffe feefeffe feefeffe  
3ffffb70:  feefeffe feefeffe feefeffe feefeffe  
3ffffb80:  feefeffe feefeffe feefeffe feefeffe  
3ffffb90:  feefeffe feefeffe feefeffe feefeffe  
3ffffba0:  feefeffe feefeffe feefeffe feefeffe  
3ffffbb0:  feefeffe feefeffe feefeffe feefeffe  
3ffffbc0:  feefeffe feefeffe feefeffe feefeffe  
3ffffbd0:  feefeffe feefeffe feefeffe feefeffe  
3ffffbe0:  feefeffe feefeffe feefeffe feefeffe  
3ffffbf0:  feefeffe feefeffe feefeffe feefeffe  
3ffffc00:  feefeffe feefeffe feefeffe feefeffe  
3ffffc10:  feefeffe feefeffe feefeffe feefeffe  
3ffffc20:  feefeffe feefeffe feefeffe feefeffe  
3ffffc30:  feefeffe feefeffe feefeffe feefeffe  
3ffffc40:  feefeffe feefeffe feefeffe feefeffe  
3ffffc50:  feefeffe feefeffe feefeffe feefeffe  
3ffffc60:  feefeffe feefeffe feefeffe feefeffe  
3ffffc70:  feefeffe feefeffe feefeffe feefeffe  
3ffffc80:  feefeffe feefeffe feefeffe feefeffe  
3ffffc90:  feefeffe feefeffe feefeffe feefeffe  
3ffffca0:  feefeffe feefeffe feefeffe feefeffe  
3ffffcb0:  feefeffe feefeffe feefeffe feefeffe  
3ffffcc0:  feefeffe feefeffe feefeffe feefeffe  
3ffffcd0:  feefeffe feefeffe feefeffe feefeffe  
3ffffce0:  feefeffe feefeffe feefeffe feefeffe  
3ffffcf0:  feefeffe feefeffe feefeffe feefeffe  
3ffffd00:  feefeffe feefeffe feefeffe feefeffe  
3ffffd10:  feefeffe feefeffe feefeffe feefeffe  
3ffffd20:  00000000 00000000 0000001f 40100178  
3ffffd30:  feefeffe feefeffe 3fffc228 40101589  
3ffffd40:  4000050c feefeffe feefeffe feefeffe  
3ffffd50:  401001fb 00000030 00000000 fffffc00  
3ffffd60:  401001f8 00000003 6000001c 3ffe864d  
3ffffd70:  00000000 00000000 00000000 fffffffe  
3ffffd80:  ffffffff 3fffc6fc 00000001 00000020  
3ffffd90:  401001b0 3fffc200 00000022 00000030  
3ffffda0:  00000005 00000000 00000020 40100178  
3ffffdb0:  401001fb 00000030 00000005 401049e8  
3ffffdc0:  00000005 00000000 00000020 40100178  
3ffffdd0:  3ffe864d 00000000 00000005 401049e8  
3ffffde0:  3ffe864d 00000000 0000000a 402027d9  
3ffffdf0:  3ffe864d 00000000 0000000a 402027d9  
3ffffe00:  3ffe864d 00000000 530a0031 402027d9  
3ffffe10:  3ffe8611 00000000 530a0031 00000022  
3ffffe20:  4020117c 3ffee334 3ffe864b 40201188  
3ffffe30:  4020117c 3ffee334 3ffe864b 40201385  
3ffffe40:  3fffc200 00000001 3ffee334 402013d8  
3ffffe50:  3fffc200 401001b0 3ffee334 40201424  
3ffffe60:  3fffc200 401001b0 00000020 40100105  
3ffffe70:  3fffc200 401001b0 00000020 401001f8  
3ffffe80:  3fffc200 401001b0 3fffc230 4000050c  
3ffffe90:  00000000 00000000 0000001f 40100178  
3ffffea0:  40100199 00000001 3fffc228 40101589  
3ffffeb0:  4000050c 00000000 00000000 fffffffe  
3ffffec0:  40100ce5 00000030 00000010 ffffffff  
3ffffed0:  40100ce5 00000000 00000001 00000001  
3ffffee0:  3fffdab0 00000000 3fffd9d0 3ffee39c  
3ffffef0:  00000000 00000000 00000001 3ffe84e0  
3fffff00:  00000000 3fffdad0 3ffee39c 00000030  
3fffff10:  00000790 000000f2 000000f2 40100784  
3fffff20:  3ffef10e 0000000a 3fffff8c 3ffee39c  
3fffff30:  3fffdad0 3ffee314 00000020 40100a23  
3fffff40:  4020117c 3ffee334 3ffe864b 40201385  
3fffff50:  3fffdad0 00000022 3fffff80 4020150d  
3fffff60:  007a1200 30c3b5cb 3ffee300 4020152c  
3fffff70:  00000000 3ffee314 3ffee334 402010d8  
3fffff80:  00000000 00000000 00000001 40100178  
3fffff90:  3fffdad0 00000000 3ffee35c 40100199  
3fffffa0:  feefeffe 00000000 3ffee35c 40201ad9  
<<<stack<<<

 ets Jan  8 2013,rst cause:2, boot mode:(3,6)

load 0x4010f000, len 3456, room 16 
tail 0
chksum 0x84
csum 0x84
vce0e63f6
~ld`

**Comment by khoih-prog** [comment]
Hi @small-zz 

You're using the ISR not correctly.

**Serial.print(ln) function** can't be used inside ISRs, especially when the period in ms. In  special cases, you can use it only for debug, but the result can be disastrous, the outcome can be crashes.

> The catch is your function is now part of an ISR (Interrupt Service Routine), and must be lean / mean, and follow certain rules.

Please do more research about ISR and read

[Attachinterrupt](https://www.arduino.cc/reference/en/language/functions/external-interrupts/attachinterrupt/)

**Comment by small-zz** [comment]
First of all, thank you for your reply. I originally planned to use a timer to interrupt the 5ms scan key program, but the program will crash when it starts, and the test can only run normally at intervals of 1S; there are only some IO operations in the key scan, somehow, esp8266 Doesn't it support such high frequency interrupt?
[Argument_None.zip](https://github.com/khoih-prog/ESP8266TimerInterrupt/files/4743607/Argument_None.zip)

**Comment by khoih-prog** [comment]
You're doing too many things inside the ISR.

You have to restructure your code by asking these questions

1. Why do you really need to use ISR ?
2. Why you must have those complicated functions, inside ISR, called every 5, 10 ms?
3. Can you just use normal timer to fulfill the task?
4. Can you offload the ISR work to outside periodic task?

The best way to use ISR is just set a flag inside ISR, then use a timer to poll the flag to determine what to do. Remember ISR function must be **lean and mean.**

You have to understand the MCU can execute just a limited number of operations per ms. When you push it to the limit, crash is certain.

I don't think I can help any further with your code.

Good Luck,
