### ISSUE TITLE
Generating slow PWM

### ISSUE THREAD

**Issue by renatoa** [khoih-prog/ESP8266TimerInterrupt#7]
Not an issue, but a query/request: please can you give me a hint how to generate 2 seconds cycle PWM with this timer ?
More exactly 50% would mean one second on, one second off on a selected GPIO pin, 25% would mean 0.5/1.5 second ratio, etc.
Resolution needs to be about 5 millisecond, i.e. 400 steps, or 0.25% per step, for the whole cycle range.

Thank you !

**Comment by khoih-prog** [comment]
@renatoa 

Sorry that I currently have no time to help you out. You can post the request for help in related forums, such as [ESP8266 Forum](https://www.esp8266.com/viewforum.php?f=32).

If you find out a solution, please post here so that other people can benefit from your experience.
