### ISSUE TITLE
Esp8266 Reboot

### ISSUE THREAD

**Issue by satishmunot** [khoih-prog/ESP8266TimerInterrupt#9]
ESP8266 Stuck and Reboot while Smart Config is in Running
Arduino IDE V1.8.13 is use

#include <Arduino.h>
#include "ESP8266TimerInterrupt.h"
#include <ESP8266WiFi.h>

#define TIMER_INTERVAL_MS   10
#define OneSec              100//1*1000/TIMER_INTERVAL_MS  // Timer Interval is 10ms
#define FourMinCnt          24000//4*60*1000/TIMER_INTERVAL_MS// For Smart Config Time 
#define FourMinCnt          24000//4*60*1000/TIMER_INTERVAL_MS// For Smart Config Time Out

unsigned int ProcessTrack;
unsigned int SmartConfigTO;
unsigned int serTmou;
unsigned int SrState;
unsigned int OneSecCnt;

ESP8266Timer ITimer;

void IRAM_ATTR TimerHandler()
{
  if(serTmout)
  {
    serTmout--;
    if(serTmout==0)
    {
      SrState = 0; 
    }
  }
  if(OneSecCnt)
  {
    OneSecCnt--;
  }
  if(SmartConfigTO)
  {
    SmartConfigTO--;
  }
}

void setup() 
{
  unsigned char cnn=0;
  Serial.begin(115200);
  Serial.flush();
  timeClient.begin();  
  WiFi.mode(WIFI_STA);// start Esp8266 WiFi Module in station mode
  ITimer.attachInterruptInterval(TIMER_INTERVAL_MS * 1000, TimerHandler);
}
void loop()
{
//piece code in loop
      switch(ProcessTrack)
      {
      case 1:WiFi.beginSmartConfig();// Smart Config Commd Set
        SmartConfigTO=FourMinCnt;// Set Smart Config Time Out for 4Min
        OneSecCnt=OneSec;;// Load One Sec Count
        ProcessTrack++;// in Next Timer ISR Case 2 will be executed
        break;
      case 2:if(SmartConfigTO)// Time out for Smart Config is Not Over
              {
              if(OneSecCnt==0) 
                {
              OneSecCnt=OneSec;// reload One Sec Count
              if(WiFi.smartConfigDone())// Smart Config Command Sucessful
                {
                sendCmdSucessFulMes();// Send Message to Serial Port
                WiFi.setAutoConnect(true);        
                }
                else
                {
                SendBusyMes();// send Busy Message to Serial Port  
                }
              }
            }
            else
            {
            SendErrorMes(); 
            }
        break;
}

When EspTouch Application Run from Cell Phone it Busy Message Correctly for 3-4 Sec and then Reboot the Esp8266

EspTouch Cell Phone App from Play Store is use for Smart Config &  sendCmdSucessFulMes(""); Send out to serial port  

Steps to reproduce the behavior. Including the [MRE](https://stackoverflow.com/help/minimal-reproducible-example) sketches

Smart Config Should be done and

### Actual behavior

Reboot Esp8266

### Information

Please ensure to specify the following:

* Arduino IDE version (e.g. 1.8.13) or Platform.io version
* `ESP8266`,`ESP32` or `STM32` Core Version (e.g. ESP8266 core v2.7.4, ESP32 v1.0.5 or STM32 v1.9.0)
* Contextual information (e.g. what you were trying to achieve)
* Simplest possible steps to reproduce
* Anything that might be relevant in your opinion, such as:
  * Operating system (Windows, Ubuntu, etc.) and the output of `uname -a`
  * Network configuration
  
### Example

```
Arduino IDE version: 1.8.13
ESP32 Core Version 1.0.5
OS: Ubuntu 20.04 LTS
Linux xy-Inspiron-3593 5.4.0-66-generic #74-Ubuntu SMP Wed Jan 27 22:54:38 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

Context:
I encountered an endless loop while trying to connect to Local WiFi.

Steps to reproduce:
1. ...
2. ...
3. ...
4. ...
```

**Comment by khoih-prog** [comment]
Thanks for your interest in the library.

But sorry, nobody has time to solve the problem for you. The library's issue here must be used only when **you prove there is some bug of the library.**

It's extremely hard for anyone to do anything to help you get out of the mess, considering with the **careless way** to post the MRE to ask for help,

Good Luck,
